- direction: 'vertical'
- name: 'send'
  service: '/send'
  image: "package://hsr_task_common/icons/exec.png"
  image_size: [80, 80]
  column: 0
- name: 'save'
  service: '/save'
  image: "package://hsr_task_common/icons/exec.png"
  image_size: [80, 80]
  column: 1
